Nov-26 01:18:17.193 [main] DEBUG nextflow.cli.Launcher - $> nextflow run main.nf
Nov-26 01:18:17.328 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.10.3
Nov-26 01:18:17.361 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/user/.nextflow/plugins; core-plugins: nf-amazon@1.11.1,nf-azure@0.14.2,nf-codecommit@0.1.2,nf-console@1.0.4,nf-ga4gh@1.0.4,nf-google@1.4.5,nf-tower@1.5.6,nf-wave@0.5.2
Nov-26 01:18:17.377 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Nov-26 01:18:17.378 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Nov-26 01:18:17.382 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Nov-26 01:18:17.399 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Nov-26 01:18:17.428 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /home/user/cloud-batch-sandbox/alphafold/nextflow/nextflow.config
Nov-26 01:18:17.430 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/user/cloud-batch-sandbox/alphafold/nextflow/nextflow.config
Nov-26 01:18:17.466 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Nov-26 01:18:18.358 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declararion
Nov-26 01:18:18.393 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [infallible_archimedes] DSL2 - revision: bf36f65d3b
Nov-26 01:18:18.394 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[nf-google@1.4.5]
Nov-26 01:18:18.395 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[nf-google@1.4.5]
Nov-26 01:18:18.395 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-google version: 1.4.5
Nov-26 01:18:18.418 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-google@1.4.5' resolved
Nov-26 01:18:18.418 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-google@1.4.5'
Nov-26 01:18:18.479 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-google@1.4.5
Nov-26 01:18:18.502 [main] DEBUG nextflow.secret.LocalSecretsProvider - Secrets store: /home/user/.nextflow/secrets/store.json
Nov-26 01:18:18.509 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@20b9d5d5] - activable => nextflow.secret.LocalSecretsProvider@20b9d5d5
Nov-26 01:18:18.616 [main] DEBUG nextflow.Session - Session UUID: 3240afd7-7702-4e1b-ba6b-2b032a1a88ca
Nov-26 01:18:18.617 [main] DEBUG nextflow.Session - Run name: infallible_archimedes
Nov-26 01:18:18.617 [main] DEBUG nextflow.Session - Executor pool size: 8
Nov-26 01:18:18.909 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=24; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Nov-26 01:18:18.940 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 22.10.3 build 5834
  Created: 21-11-2022 21:37 UTC 
  System: Linux 5.15.65+
  Runtime: Groovy 3.0.13 on OpenJDK 64-Bit Server VM 17.0.5+8
  Encoding: UTF-8 (ANSI_X3.4-1968)
  Process: 3862@jk-af-dev-1 [172.17.0.3]
  CPUs: 8 - Mem: 31.4 GB (23.7 GB) - Swap: 0 (0)
Nov-26 01:18:18.981 [main] DEBUG nextflow.file.FileHelper - Can't check if specified path is NFS (1): gs://jk-aff-bucket/nextflow/alphafold

Nov-26 01:18:18.982 [main] DEBUG nextflow.Session - Work-dir: gs://jk-aff-bucket/nextflow/alphafold [null]
Nov-26 01:18:18.982 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/user/cloud-batch-sandbox/alphafold/nextflow/bin
Nov-26 01:18:19.013 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[GoogleLifeSciencesExecutor, GoogleBatchExecutor]
Nov-26 01:18:19.033 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Nov-26 01:18:19.070 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Nov-26 01:18:19.088 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 9; maxThreads: 1000
Nov-26 01:18:19.204 [main] DEBUG nextflow.Session - Session start
Nov-26 01:18:19.673 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Nov-26 01:18:19.827 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: google-batch
Nov-26 01:18:19.827 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'google-batch'
Nov-26 01:18:19.829 [main] DEBUG nextflow.executor.Executor - [warm up] executor > google-batch
Nov-26 01:18:19.842 [main] DEBUG n.processor.TaskPollingMonitor - Creating task monitor for executor 'google-batch' > capacity: 1000; pollInterval: 10s; dumpInterval: 5m 
Nov-26 01:18:19.853 [main] DEBUG nextflow.cloud.google.GoogleOpts - Google auth via application DEFAULT
Nov-26 01:18:19.855 [main] DEBUG n.c.google.batch.GoogleBatchExecutor - [GOOGLE BATCH] Executor config=BatchConfig[googleOpts=GoogleOpts(projectId:jk-af-final, credsFile:null, location:us-central1, enableRequesterPaysBuckets:false, credentials:UserCredentials{requestMetadata=null, temporaryAccess=null, clientId=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com, refreshToken=1//04TeYasF5Wt-aCgYIARAAGAQSNwF-L9IreE6e7Xh_jRYGtCjynrOTKzDGN70ew8Df_WiLYv8Zalpi5DfqrUWhqfr4uQMrf5faWuE, tokenServerUri=https://oauth2.googleapis.com/token, transportFactoryClassName=com.google.auth.oauth2.OAuth2Utils$DefaultHttpTransportFactory, quotaProjectId=jk-af-final})
Nov-26 01:18:19.879 [main] DEBUG n.c.google.batch.client.BatchClient - [GOOGLE BATCH] Creating service client with config credentials
Nov-26 01:18:20.641 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: run_data_pipeline
Nov-26 01:18:20.642 [main] DEBUG nextflow.Session - Igniting dataflow network (2)
Nov-26 01:18:20.643 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > run_data_pipeline
Nov-26 01:18:20.645 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination 
Nov-26 01:18:20.645 [main] DEBUG nextflow.Session - Session await
Nov-26 01:18:22.263 [Task submitter] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] submitted > job=nf-c4230354-1669425501218; uid=j-427f7b33-7f34-4904-b4d3-5b34d43c91a3; work-dir=gs://jk-aff-bucket/nextflow/alphafold/c4/23035405d5a58b8f0dbd19d4a495fc
Nov-26 01:18:22.264 [Task submitter] INFO  nextflow.Session - [c4/230354] Submitted process > run_data_pipeline (1)
Nov-26 01:21:09.905 [Task monitor] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Terminated job=nf-c4230354-1669425501218; state=FAILED
Nov-26 01:21:10.744 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: run_data_pipeline (1); status: COMPLETED; exit: 1; error: -; workDir: gs://jk-aff-bucket/nextflow/alphafold/c4/23035405d5a58b8f0dbd19d4a495fc]
Nov-26 01:21:10.875 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'run_data_pipeline (1)'

Caused by:
  Process `run_data_pipeline (1)` terminated with an error exit status (1)

Command executed:

  python /runners/run_test.py '--text=Bonjour' '--features_path=features.pkl' '--msas_path=msas'

Command exit status:
  1

Command output:
  (more omitted..)
  3e45a0c08bfc: Download complete
  6008555da505: Verifying Checksum
  6008555da505: Download complete
  6133a7670aff: Verifying Checksum
  6133a7670aff: Download complete
  0047db6c2358: Download complete
  d9960804702f: Download complete
  e2250e4b9e64: Verifying Checksum
  e2250e4b9e64: Download complete
  320b8621e9d3: Verifying Checksum
  320b8621e9d3: Download complete
  be7a8828f4d2: Download complete
  1b53decda963: Verifying Checksum
  1b53decda963: Download complete
  07414aeb81b6: Verifying Checksum
  07414aeb81b6: Download complete
  e2250e4b9e64: Pull complete
  9cf40c59065f: Pull complete
  5e609a938304: Pull complete
  f3f2f506d212: Pull complete
  b4ca963de55e: Pull complete
  83a0e5e3c82b: Pull complete
  07414aeb81b6: Pull complete
  3e45a0c08bfc: Pull complete
  6008555da505: Pull complete
  6133a7670aff: Pull complete
  0047db6c2358: Pull complete
  d9960804702f: Pull complete
  be7a8828f4d2: Pull complete
  320b8621e9d3: Pull complete
  1b53decda963: Pull complete
  Digest: sha256:9c70f5edda8241cbed45c5caf5196c24ae87614f6d65141d0f07f5a027249d4a
  Status: Downloaded newer image for gcr.io/jk-af-final/alphafold:latest
  gcr.io/jk-af-final/alphafold:latest
  /opt/conda/lib/python3.7/site-packages/haiku/_src/data_structures.py:37: FutureWarning: jax.tree_structure is deprecated, and will be removed in a future release. Use jax.tree_util.tree_structure instead.
    PyTreeDef = type(jax.tree_structure(None))
  I1126 01:20:54.153501 139995707717440 run_test.py:36] Running test
  I1126 01:20:54.153621 139995707717440 run_test.py:37] Bonjour
  I1126 01:20:54.153683 139995707717440 run_test.py:40] Saving features to features.pkl
  Bonjour
  Traceback (most recent call last):
    File "/runners/run_test.py", line 49, in <module>
      app.run(_main)
    File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
      _run_main(main, args)
    File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
      sys.exit(main(argv))
    File "/runners/run_test.py", line 45, in _main
      with open(os.path.join(FLAGS.msas_path, 'test.fasta')) as f:
  FileNotFoundError: [Errno 2] No such file or directory: 'msas/test.fasta'

Command error:
  /opt/conda/lib/python3.7/site-packages/haiku/_src/data_structures.py:37: FutureWarning: jax.tree_structure is deprecated, and will be removed in a future release. Use jax.tree_util.tree_structure instead.
    PyTreeDef = type(jax.tree_structure(None))
  I1126 01:20:54.153501 139995707717440 run_test.py:36] Running test
  I1126 01:20:54.153621 139995707717440 run_test.py:37] Bonjour
  I1126 01:20:54.153683 139995707717440 run_test.py:40] Saving features to features.pkl
  Traceback (most recent call last):
    File "/runners/run_test.py", line 49, in <module>
      app.run(_main)
    File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
      _run_main(main, args)
    File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
      sys.exit(main(argv))
    File "/runners/run_test.py", line 45, in _main
      with open(os.path.join(FLAGS.msas_path, 'test.fasta')) as f:
  FileNotFoundError: [Errno 2] No such file or directory: 'msas/test.fasta'

Work dir:
  gs://jk-aff-bucket/nextflow/alphafold/c4/23035405d5a58b8f0dbd19d4a495fc

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
Nov-26 01:21:10.887 [main] DEBUG nextflow.Session - Session await > all processes finished
Nov-26 01:21:10.921 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `run_data_pipeline (1)` terminated with an error exit status (1)
Nov-26 01:21:11.059 [main] DEBUG nextflow.Session - Session await > all barriers passed
Nov-26 01:21:11.136 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=841ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ]
Nov-26 01:21:11.146 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Nov-26 01:21:11.146 [main] INFO  org.pf4j.AbstractPluginManager - Stop plugin 'nf-google@1.4.5'
Nov-26 01:21:11.146 [main] DEBUG nextflow.plugin.BasePlugin - Plugin stopped nf-google
Nov-26 01:21:11.165 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
